sudo: false
language: php

addons:
    mariadb: '10.2'
    hosts:
        - pimcore-test.dev
services:
    - mysql
env:
    global:
        - PIMCORE_ENVIRONMENT=test
        - PIMCORE_TEST_DB_DSN="mysql://root@localhost/coreshop_test"
        - PIMCORE_VERSION="^5"
        - CORESHOP_TEST=1
        - CORESHOP_SUITE=application

matrix:
    include:
        - sudo: required
          php: 7.1
          env:
            - CORESHOP_SUITE=codestyle

        - sudo: required
          php: 7.2
          env:
            - CORESHOP_SUITE=stan
            - PIMCORE_VERSION="~5.6.0"

        - sudo: required
          php: 7.2
          env:
            - CORESHOP_SUITE=stan
            - PIMCORE_VERSION="^5.7.2"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="~5.4.0"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="~5.4.0"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="~5.5.0"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="~5.5.0"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="~5.6.0"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="~5.6.0"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="~5.7.2"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="~5.7.2"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="5.8.x-dev"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="5.8.x-dev"
    allow_failures:
        - env:
            - CORESHOP_SUITE=codestyle
        - env:
            - PIMCORE_VERSION="5.8.x-dev"
    fast_finish: true

cache:
    directories:
        - $HOME/.cache/composer

install:
    - etc/travis/install

script:
    - etc/travis/script

notifications:
    email:
        - travis-ci@coreshop.org
