default:
    formatters:
        pretty:
            verbose: true
            paths: false
            snippets: false

    extensions:
        FriendsOfBehat\SymfonyExtension:
            bootstrap: tests/behat-bootstrap.php
            kernel:
                path: app/BehatAppKernel.php
                class: BehatAppKernel
                environment: behat
