name: Behat
on:
  push:
    branches: [ master, '3.0' ]
  pull_request:
    branches: [ master, '3.0' ]

jobs:
  behat:
    runs-on: ubuntu-latest
    env:
      PIMCORE_ENVIRONMENT: "test"
      CORESHOP_TEST: 1
      PIMCORE_TEST_DB_DSN: "mysql://root:root@172.0.0.1/coreshop_test"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: coreshop_test
        ports:
          - 3306
        pptions: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        pimcore: [~6.5.0, dev-master]
        symfony: [~3.4, ^4.0]

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Check PHP Version
      run: php -v
      
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql -uroot -h127.0.0.1 -proot -e "SHOW DATABASES"

    - name: Setup mysql
      run: |
        mysql -uroot -h127.0.0.1 -proot -e -e "SET GLOBAL innodb_file_format=Barracuda;"
        mysql -uroot -h127.0.0.1 -proot -e -e "SET GLOBAL innodb_large_prefix=1;"
        mysql -uroot -h127.0.0.1 -proot -e -e "CREATE DATABASE coreshop_test CHARSET=utf8mb4;"

    - name: Copy parameters.yml
      run: cp app/config/parameters.example.yml app/config/parameters.yml

    - name: Composer install
      run: |
        composer config minimum-stability dev
        composer config prefer-stable true
        COMPOSER_MEMORY_LIMIT=-1 composer req pimcore/pimcore:{{ matrix.pimcore }} symfony/symfony:{{ matrix.symfony }} --no-interaction --no-scripts --no-update
        COMPOSER_MEMORY_LIMIT=-1 composer install -o --no-interaction

    - name: Cache clear
      run: bin/console cache:clear

    - name: Assets Install
      run: bin/console assets:install --symlink web

    - name: Run Behat
      run: vendor/bin/behat --strict --no-interaction -vvv -f progress --config behat.yml.dist
