name: Behat
on:
  push:
    branches: [ master, '3.0' ]
  pull_request:
    branches: [ master, '3.0' ]

jobs:
  behat:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: coreshop_test
        ports:
          - 3306
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        pimcore: [~6.5.0, dev-master]
        symfony: [~3.4, ^4.0]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Mysql
      run: |
        mysql --version
        mysql -e "SET GLOBAL innodb_file_format=Barracuda;"
        mysql -e "SET GLOBAL innodb_large_prefix=1;"
        mysql -e "CREATE DATABASE coreshop_test CHARSET=utf8mb4;"

    - name: Copy parameters.yml
      run: cp app/config/parameters.example.yml app/config/parameters.yml

    - name: Composer install
      run: |
        composer config minimum-stability dev
        composer config prefer-stable true
        COMPOSER_MEMORY_LIMIT=-1 composer req pimcore/pimcore:{{ matrix.pimcore }} symfony/symfony:{{ matrix.symfony }} --no-interaction --no-scripts --no-update
        COMPOSER_MEMORY_LIMIT=-1 composer install -o --no-interaction

    - name: Cache clear
      run: bin/console cache:clear

    - name: Assets Install
      run: bin/console assets:install --symlink web

    - name: Run Behat
      run: vendor/bin/behat --strict --no-interaction -vvv -f progress --config behat.yml.dist
