name: Composer Validate
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Validate composer.json in packages
      run: |
        packages="$(find "src/CoreShop" -mindepth 3 -maxdepth 3 -type f -name composer.json -exec dirname '{}' \;)"

        for package in $packages
        do
            echo "Validating Package" "$(basename "$package")"
            composer validate --ansi --strict $package/composer.json
        done
