name: Lint
on:
  push:
    branches: [ master, '3.0' ]
  pull_request:
    branches: [ master, '3.0' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: intl

    - name: Copy parameters.yml
      run: cp app/config/parameters.example.yml app/config/parameters.yml

    - name: Composer install
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Validate YAML
      run: bin/console lint:yaml src --no-debug

    - name: Validate TWIG
      run: bin/console lint:twig src --no-debug
